server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${SSH_HOST}:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Tự động cập nhật cấu trúc bảng dựa trên entity
    show-sql: true  # Hiển thị SQL câu lệnh trong log
    properties:
      hibernate:
        format_sql: true  # Định dạng SQL câu lệnh
        use_sql_comments: true  # Sử dụng comment trong SQL
        generate_statistics: true  # Bật thống kê Hibernate

logging:
  level:
    org.hibernate.SQL: DEBUG  # Hiển thị câu lệnh SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Hiển thị giá trị bind
