# .docker/phpmyadmin/Dockerfile

FROM phpmyadmin/phpmyadmin:latest

ENV PMA_HOST=${PMA_HOST}
ENV PMA_PORT=${PMA_PORT}
ENV PMA_USER=${PMA_USER}
ENV PMA_PASSWORD=${PMA_PASSWORD}

EXPOSE ${PHPMYADMIN_PORT}
